# Generated by Django 5.0.3 on 2024-04-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_room_image_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_reserved',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
