# Generated by Django 5.0.3 on 2024-04-11 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_room_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
