# Generated by Django 5.0.3 on 2024-04-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_room_images_room_image_delete_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/room_images/'),
        ),
    ]
