# Generated by Django 5.0.4 on 2024-05-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_service_reservation_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
